### ISSUE TITLE
DATA_SCOPE errors logged on startup

### ISSUE THREAD

**Issue by theganyo** [30x/apidAnalytics#5]
Seeing this logged on startup:

> ERRO[0000] Count not get datascope from DB due to: no such table: DATA_SCOPE  module=apidAnalytics
> DEBU[0000] query: SELECT mp.tenant_id, mp.appcred_id, ap.name, a.name, d.username, d.email FROM APP_CREDENTIAL_APIPRODUCT_MAPPER as mp INNER JOIN API_PRODUCT as ap ON ap.id = mp.apiprdt_id INNER JOIN APP AS a ON a.id = mp.app_id INNER JOIN DEVELOPER as d ON d.id = a.developer_id; args: []driver.Value{}  module=data_trace
> ERRO[0000] Count not get developerInfo from DB due to: no such table: APP_CREDENTIAL_APIPRODUCT_MAPPER  module=apidAnalytics

(BTW: Wondering why it needs access to DB for that at all? Seems like just grabbing the info straight from the snapshot and/or change messages would be sufficient.)

**Comment by pjain404** [comment]
The plugin needs to extract scope and developer related information from the DB for every analytics record. 

It provides 2 options
1. use caching
In this case, it tries to create a cache on start up and then refreshes cache on every new change. 

2. no caching 
In this case, every time it gets this info from the DB

I was querying the DB for creating cache assuming when the snapshot event arrives, it implies db is updated. Since, that is not true - I will update the code to create initial cache from snapshot instead of DB.
